name: reforge
channels:
  - conda-forge
dependencies:
  - python>=3.13
  - cython
  - cupy
  - matplotlib
  - memory_profiler
  - mdanalysis
  - mdtraj
  - numpy 
  - openmm>=8.3.1
  - selenium
  - setuptools
  - scikit-learn
  - packaging
  - pandas
  - pdbfixer
  - pytest
  - vermouth
  - webdriver-manager
