name: Build and Deploy Docs

on:
  push:
    branches: [ main ]  # Only deploy docs on main branch
  workflow_dispatch:  # Allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated version
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v4  # Updated version
        with:
          python-version: '3.12'  # Specific version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install Sphinx and documentation dependencies
          pip install sphinx sphinx-rtd-theme sphinx-gallery
          # Install minimal project dependencies (skip heavy ones like CUDA)
          pip install numpy matplotlib pandas
          # Try to install project in development mode (may fail, that's ok)
          pip install -e . || echo "Failed to install project, continuing..."

      - name: Build Sphinx Documentation
        working-directory: docs
        run: |
          make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Use default token
          publish_dir: docs/build/html

